# Generated by Django 4.0.6 on 2022-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alert_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.FloatField(),
        ),
    ]
